fix the deployment file 8

diff --git a/.github/workflows/terraform-deploy.yml b/.github/workflows/terraform-deploy.yml
--- a/.github/workflows/terraform-deploy.yml
+++ b/.github/workflows/terraform-deploy.yml
@@ -27,17 +27,23 @@ jobs:
         uses: unfor19/install-aws-cli-action@v1
         with:
           version: 2
-      - name: Debug Role ARN
-        run: echo "Role ARN: ${{ secrets.AWS_ASSUME_ROLE_DEV }}"
+      
       - name: Assume Role
         id: assume-role
         shell: bash
         run: |
-          role_output=$(aws sts assume-role --role-arn "${{ secrets.AWS_ASSUME_ROLE_DEV }}" --role-session-name "DevopsAdmin-Session" --output json)
+          role_output=$(aws sts assume-role --role-arn "${{ secrets.AWS_ASSUME_ROLE }}" --role-session-name "DevopsAdmin-Session" --output json)
+
+          if [ -z "$role_output" ]; then
+            echo "Failed to assume role"
+            exit 1
+          fi
+
           echo "Assumed role output: $role_output"
           echo "AWS_ACCESS_KEY_ID=$(echo $role_output | jq -r .Credentials.AccessKeyId)" >> $GITHUB_ENV
           echo "AWS_SECRET_ACCESS_KEY=$(echo $role_output | jq -r .Credentials.SecretAccessKey)" >> $GITHUB_ENV
           echo "AWS_SESSION_TOKEN=$(echo $role_output | jq -r .Credentials.SessionToken)" >> $GITHUB_ENV
+          echo "AWS_REGION=${{ inputs.AWS_REGION }}" >> $GITHUB_ENV
 
       - name: Checkout
         uses: actions/checkout@v3.5.3
